### ISSUE TITLE
Merge QEMU Upstream 3.0.0 updates in

### ISSUE THREAD

**Issue by mborgerson** [xqemu/xqemu#101]
While the XQEMU code base is not too far diverged from QEMU upstream, it's probably best to keep it in sync to benefit from bug fixes.

3.0.0 was released on August 14th. I haven't inspected the changes from 2.12.0 [what I rebased XQEMU onto starting back in March/April timeframe] to 3.0.0 yet but I don't expect the differences to be too radical, and an easy merge of updates [relative to last time, anyway].

To minimize impact, this will be a merge of the 3.0.0 tag, not a rebase.

**Comment by MayeulC** [comment]
Mmm, @mborgerson, could you tell mewhat you think of https://github.com/xqemu/xqemu/issues/46#issuecomment-413686541 before merging new commits, as that could make it quite a bit more difficult to put that proposal into effect?

**Comment by mborgerson** [comment]
@MayeulC I did see your comment but haven't had a chance to give a thoughtful response yet, but I will get back to you shortly! Thanks!
