### ISSUE TITLE
Using eeprom breaks retail kernels

### ISSUE THREAD

**Issue by GXTX** [xqemu/xqemu#143]
After playing around i've found that specifying a eeprom to be loaded will stop retail kernels from booting.

**Comment by dracc** [comment]
Any retail kernels, or what kernels did you try? With what EEPROM image?

**Comment by GXTX** [comment]
Whoops! I probably should have mentioned that those.

Yeah so I have retail 1.2 and 1.6 copies, both failed in the 2 working retail kernel versions 3944 & 4034

**Comment by JayFoxRox** [comment]
> Yeah so I have retail 1.2 and 1.6 copies, both failed in the 2 working retail kernel versions 3944 & 4034

3944 and 4034 should be 1.0 EEPROM keys (for Xbox 1.0), but Xbox 1.2 and Xbox 1.6 will be 1.1 BL EEPROM keys.

Microsoft changed the keys (for each BL version); from the top of my head, there's at least 4 known EEPROM keys:

* Xbox 1.0 (X3 + 1.0 BL)
* Xbox 1.1+ (X3 + 1.1 BL)
* Debug Xbox (X2 + debug keys)
* Chihiro (X2 + chihiro keys)

So if you are using MCPX 1.0 and a 1.0 kernel, you'll require a 1.0 EEPROM.
I think this is the issue at hand. You are using MCPX 1.0 and a 1.0 kernel, but a 1.1 EEPROM (which won't decrypt correctly).

I'm not sure how an Xbox behaves if the EEPROM can not be decrypted. Please specify what exactly you mean (observe) by "stop retail kernels from booting", so we can compare this to a real Xbox.

**Comment by StrikerX3** [comment]
FWIW, I've tried to boot 4817 with an MCPX 1.1 ROM and bunnie's EEPROM. The guest loops forever trying to decrypt the third(?) 512 byte block of the kernel image.

**Comment by GXTX** [comment]
JFR you've explained this issue perfectly and I figured out what and why it was happening a few hours after posting this issue. I probably should've closed it.

**Comment by JayFoxRox** [comment]
Would be nice if you could add what you observed to your post for reference.

However: user-error; marking as invalid.

Closed.
