### ISSUE TITLE
Can't get XQEMU to run, am I doing this right?

### ISSUE THREAD

**Issue by ArcAngelRyse** [xqemu/xqemu#146]
Hello, 

I've been trying to get this to run but can't seem to find a way to get it to run any help would be nice. I've been attempting to get it to run but it keeps returning this Error. I don't know what it is or whats causing it. Running as admin didn't really help either. 

Windows 10 Pro, Latest Retail.

![annotation 2018-12-24 010612](https://user-images.githubusercontent.com/34932364/50392015-767ca300-0718-11e9-875f-62a969a6afa1.jpg)
![annotation 2018-12-24 010640](https://user-images.githubusercontent.com/34932364/50392016-77153980-0718-11e9-8325-ec984a1dafa3.jpg)
![annotation 2018-12-24 010806](https://user-images.githubusercontent.com/34932364/50392017-77153980-0718-11e9-90f2-530f0ecba4f2.jpg)

**Comment by GXTX** [comment]
Disable CPU acceleration because HAXM isn't working currently, and an xbe isn't a disc image. If it's still not working post the information in CLI..

**Comment by ArcAngelRyse** [comment]
Still gives me that same error although this time the window just opens for a bit and then closes. screenshot here. as for CLI info there.
________________________________

**Comment by ArcAngelRyse** [comment]
Still gives me that same error although this time the window just opens for a bit and then closes. screenshot here. as for CLI info there. 

![annotation 2018-12-24 024342](https://user-images.githubusercontent.com/34932364/50393755-5a7ffe00-0726-11e9-9aa1-c7bc65ca0b05.jpg)
![annotation 2018-12-24 024556](https://user-images.githubusercontent.com/34932364/50393757-5a7ffe00-0726-11e9-837b-64b4ffa3b37e.jpg)

**Comment by dracc** [comment]
Could you try another BIOS? That particular one has been known to cause trouble before. :(

**Comment by ArcAngelRyse** [comment]
> 
> 
> Could you try another BIOS? That particular one has been known to cause trouble before. :(

I have and this is the return, a bit further but not even close to booting.
![annotation 2018-12-24 040914](https://user-images.githubusercontent.com/34932364/50395508-8acd9980-0732-11e9-8604-fe4585956cd4.jpg)

**Comment by dracc** [comment]
@ArcAngelRyze Please provide your updated command line.
How was your xiso created from the xbe you tried running first? Could you try to recreate it with `extract-xiso` available from https://github.com/xboxdev/extract-xiso ?

**Comment by ArcAngelRyse** [comment]
CLI:
"X:/Program Files/Xbox/xqemu/xqemu.exe" -cpu pentium3 -machine "xbox,bootrom=X:/Program Files/Xbox/xqemu/mcpx_1_0.bin,short_animation" -m 128M -bios "X:/Program Files/Xbox/xqemu/FLASH/Xbox_MAME/xbox-5713.bin" -net nic,model=nvnet -net user -drive "file=X:/Program Files/Xbox/xqemu/xbox_hdd.qcow2,index=0,media=disk,locked" -drive "index=1,media=cdrom,file=X:/Program Files/Xbox/xqemu/roms/TimeSplitters/TimeSplitters_-_Future_Perfect_rev2.iso" -qmp tcp:localhost:4444,server,nowait -display sdl -device usb-xbox-gamepad-sdl,index=0,port=3

ISO9660 + Juliet Using daemon tools.

![annotation 2018-12-24 040914](https://user-images.githubusercontent.com/34932364/50396264-03365980-0737-11e9-864b-4cc8b1e8b25d.jpg)

**Comment by ArcAngelRyse** [comment]
The Xbe has launched in other emulators so I believe it works for the most part.

**Comment by GXTX** [comment]
The game discs used by the Xbox aren't in standard iso format, please use [extract-xiso](https://github.com/XboxDev/extract-xiso) (or similar) to create one. More information [here](http://xboxdevwiki.net/Xbox_Game_Disc).

If I remember correctly retail kernels wont load discs currently. They also wont load your HDD unless it has the signed dashboard on it (HDD loading is required to even boot into discs as it's something the kernel checks), and kernels above 4034 aren't booting at all.

Hope that helps!

**Comment by ArcAngelRyse** [comment]
> 
> 
> The game discs used by the Xbox aren't in standard iso format, please use [extract-xiso](https://github.com/XboxDev/extract-xiso) (or similar) to create one. More information [here](http://xboxdevwiki.net/Xbox_Game_Disc).
> 
> If I remember correctly retail kernels wont load discs currently. They also wont load your HDD unless it has the signed dashboard on it (HDD loading is required to even boot into discs as it's something the kernel checks), and retail kernels above 4034 aren't booting at all.
> 
> Hope that helps!

Thanks but no made no difference in the least. And just to double check I've tested other emulators for xbox that have worked just to make sure if I'm doing it right. Trial and error of course. But they've been working.

But it's mentioning stuff I don't even remember configuring, I ran it as admin in case maybe that has something to do with it. But nope.

Will this be fine? Having issues gettings windows to provide md5 for anything atm.
Name: mcpx_1_0.bin
Size: 512 bytes
SHA256: AC44F0E75AA606EC70D6E07B848D5E72326909A34F450B1730398E33CE062CD3
SHA1: A9ECBF8896D10DB81594923E485862AA3AAC7B58
CRC64: 07E69661B58914D9
CRC32: F31429FC

**Comment by ArcAngelRyse** [comment]
> 
> 
> [Please confirm your checksum of the MCPX 1.0 image](https://xqemu.com/getting-started/#mcpx-boot-rom-image).
> 
> _Also: The DVD is not checked until the animation runs. And even if the disc image is horribly broken, the Xbox [and QEMU] should still boot (or they will complain if they can't read the DVD)._

**Comment by thrimbor** [comment]
> Will this be fine? Having issues gettings windows to provide md5 for anything atm.
> Name: mcpx_1_0.bin
> Size: 512 bytes
> SHA256: AC44F0E75AA606EC70D6E07B848D5E72326909A34F450B1730398E33CE062CD3
> SHA1: A9ECBF8896D10DB81594923E485862AA3AAC7B58
> CRC64: 07E69661B58914D9
> CRC32: F31429FC

No. The correct SHA256 would be e99e3a772bf5f5d262786aee895664eb96136196e37732fe66e14ae062f20335

**Comment by JayFoxRox** [comment]
There's an MD5 sum provided on the linked website (and what you did wrong when you dumped it / hints on how to fix it).

I've generated a SHA1 and SHA256 for the correct images I use (as you did not provide a MD5 sum to compare):

SHA256: e99e3a772bf5f5d262786aee895664eb96136196e37732fe66e14ae062f20335
SHA1: 5d270675b54eb8071b480e42d22a3015ac211cef

I reconstructed a broken image and it gave the checksums you provided; so your image is definitely broken. You need to fix your MCPX image.

Closed.

**Comment by JayFoxRox** [comment]
Only MCPX 1.0 is confirmed to work; your log in the screenshots above was made with a broken MCPX image. If you still have issues, it's now another (possibly similar looking) problem, and we'd need a new log (QEMU window messages during boot) and information (does it hang? crash? what do you see?).

However, we don't provide user-support on this bug-tracker (it's assumed this is a user-error because it works for many people; so it's nothing we can fix with code = not a bug).

If you want support I suggest to find a community; [we *temporarily* provide support for users on XboxDev Discord](https://github.com/XboxDev/XboxDev#want-to-help-contact-us). But, XboxDev is meant to be a developer community, too, so we'll probably remove the emulation user-support channel soon (when we have a dedicated user-community for XQEMU).
