### ISSUE TITLE
APU memory access is slow

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/xqemu#156]
The APU uses `stb_phys(&address_space_memory, paddr, ptr[i]);` to write bytes to scratch space, and `ldub_phys(&address_space_memory, paddr);` to read from scratch space.

Instead, we should probably be using something like NV2A, where xbox.c passes the `ram_memory`, so we can access the memory directly.

The same will be relevant for the FIFOs and voices.

We also use `ldl_le_phys` to get scratch space PRDs as part of the memory access loop - that shouldn't be necessary (unless a memory access overwrites the PRD, which we should probably check for).

**Comment by espes** [comment]
might have been more idiomatic to just use `dma_buf_read`/`dma_buf_write`

**Comment by JayFoxRox** [comment]
Oops! I didn't know about these. I'll continue with the `memory_region` code for now, but we can change it to the `dma` functions later maybe (I'll have to read up on it).
