### ISSUE TITLE
Add xqemu-manager to appveyor artifacts

### ISSUE THREAD

**Issue by mborgerson** [xqemu/xqemu#18]

**Comment by ObiKKa** [comment]
It seems you've already [done](https://github.com/xqemu/xqemu-manager/commit/34a901523df0c9fc3759415ac4f483603d5e09b2) this for Windows builds.

**Comment by mborgerson** [comment]
Yes we've discussed this in chat but failed to accurately capture this in GitHub. The real issue here is currently that xqemu and xqemu-manager are distributed separately, which is inconvenient for users--they should somehow be combined. It's probably better to do it through xqemu-manager as we can build in an auto-updater more easily. We have an issue filed some time back here: https://github.com/xqemu/xqemu-manager/issues/17. I'll close this issue for now as I think it makes more sense to track on the xqemu-manager repository.
