### ISSUE TITLE
Add xiso check on disc images

### ISSUE THREAD

**Issue by LittleStinky123** [xqemu/xqemu#220]
At the moment xqemu only checks if the disk image exists.
If it can't be opened after the vm booted up, for example if it is a backup made with a kreon drive, there is no error message displayed.
Adding a check for that would be nice as there isn't anything of the iso format mentioned on the official website.

**Comment by GXTX** [comment]
Redump style ISOs being broken is just a bug (#37), and you are free to put any type of disk into your real Xbox, why not XQEMU?

**Comment by LittleStinky123** [comment]
Sorry, I didn't know they were called redump isos.
Then I would have probably found the issue and wouldn't have opened this one.

**Comment by JayFoxRox** [comment]
This repository is for the Xbox hardware emulation. As @GXTX correctly said: a hardware drive does not check if the disc you insert is correctly formatted.

XQEMU is not making any assumptions about how you'd use your virtual Xbox hardware.
This is similar to what would happen if you inserted a burned CD into a real Xbox: the running OS will choose how to signal the error. This should not be the emulators responsibility (which attempts to remain neutral / not be invasive; especially with LLE).

You should have the ability to insert an audio-CD, a video DVD, a data DVD, or any other kind of disc medium (different sizes / different filesystems / ...) into your physical or virtual Xbox. And XQEMU allows this.
This would also be expected by some Xbox applications, Linux or reactOS. Adding too many Xbox constraints to the hardware layer would be bad.

We did discuss a warning for users, and this can be acceptable (if it's only a warning); but it would belong into the GUI, which is currently mostly in https://github.com/xqemu/xqemu-manager/ . Some work of disc identification has been done in [this code of PR 37](https://github.com/xqemu/xqemu-manager/pull/37/files#diff-5bc02cefb3ea9e27f1a6776eabd1935dR35) (which is likely to be rejected for other reasons).

Closed (belongs into UI / not suitable for LLE).
