### ISSUE TITLE
Building on Appveyor is broken

### ISSUE THREAD

**Issue by GXTX** [xqemu/xqemu#221]
While testing something on my own fork I noticed that the build system for appveyor is broken. I've narrowed this down to an issue with doing a `sysupgrade` to the MSYS environment. This is because to do a `sysupgrade` you're required to close the msys shell and rerun the command after doing it once.

This problem has been there since the project began using appveyor, it just went unnoticed as everything is very verbose and only just now became a real problem as base packages are starting to update upstream.

Some solutions for this are:

1. manually updating the single broken package `libreadline`
(isn't the best option as we'll face the same issue in the future with other packages)
2. figuring out a way to relaunch the msys shell after the first `sysupgrade`
(likely hard)
3. just updating packages we deem necessary to be up-to-date
(likely the best option)

**Comment by binarymaster** [comment]
Confirming the issue. Please push a workaround commit, since it's the only possible and preferred way for me to build XQEMU.

**Comment by JayFoxRox** [comment]
@binarymaster please do not use our CI systems for building XQEMU. CI is meant for finding errors in builds on all supporting platforms and providing, trusted, temporary builds to our users.
Unless you want to do these things (you typically don't, until you send a PR), avoid using CI.

On some CI systems, our fork network activity will affect our build queue and delay official builds. It's also abuse of free-for-open-source infrastructure which affects other users which depend on it.

Instead, build locally - this is supported on all major platforms with free software.
If you can't run toolchains locally, look into other options, such as local VMs, cross-compilation etc.
