### ISSUE TITLE
xgl breakage under X11(linux)

### ISSUE THREAD

**Issue by JazzMaster** [xqemu/xqemu#227]
1- dont use Xgl- use GLU,GLEW,GLUT,freeglut(or glfw)
use of xgl can break the running system(a no no)
2- it looks like X11 graphics are rendering onto a GL context. YOu should be using one provided by qemu for the simulated gfx buffer- not trying to render onto a GL context directly.

you can see this with ubu18+ with slayers disc. It does boot- you see the slayers logo and then X11 locks up after the screen goes dark. This is not a qemu fault- its an xbox fault with xqemu- not writing (or overrendering) to the inappropriate output buffer(or trying to write to the physical screen via nv instructions(im on ATI hardware) and breaking X11.

noted in output of xqemu is gloffscreen.c: glx references.

**Comment by mborgerson** [comment]
> 1- dont use Xgl- use GLU,GLEW,GLUT,freeglut(or glfw)
> use of xgl can break the running system(a no no)
> 2- it looks like X11 graphics are rendering onto a GL context. YOu should be using one provided by qemu for the simulated gfx buffer- not trying to render onto a GL context directly.
Currently we use GLX to create a context to be used for offscreen rendering. The rendered surfaces are synchronized back to system memory, and then displayed via the QEMU display device. We use epoxy (alternative to GLEW) to handle loading GL functions.

So far this has not been an issue, but perhaps there is an issue with AMD drivers. Are you stating that your entire X server locks up when running XQEMU or just XQEMU itself? Does this happen only with the particular application you are trying to run? Have you tried on other platforms?

**Comment by JazzMaster** [comment]
exactly what Im saying. 

But im not sure its an Xgl issue-(although syntacticly XGL is a mess compared to the alternative) its a GL issue- for sure. 

The issue that we are over rendering- choking system resources. X11- as the window manager- doesnt like this- but cant stop us. 

-but we have to render in a loop sometimes-

Neither SDL nor GL nor GLUT programmers seem be working thru this issue.

I just hit the bug with this demo code- mind you in pascal(fpc). nm the unit its supposed to work with- (it appears library chaining is impossible with OGL contexts?)

What appears to trigger this is a rendering loop that does not sleep- ever. <br>
60Hz is abt 17ms, 120 about half of that. <br>
Its about timings and process(thread) sleeping and/or resources.

language Delay and sleep() functions- maybe mine are bad- dont seem to help. 

You need to trip the video callback(as -or thru- a timer)-if you dont have one- USE ONE- to render at the Hz(fps) you are aiming for- then release the remaining CPU resources for input, processing,etc.

When you render continuously- you CAUSE this issue. 
As I said- everyone says to render- inside a mainloop(or loop)- and forgets that theres no stopping the runaway video train.

 glutDisplayFunc(@Draw);
is the looped video renderer in this case.
Anything other than waiting on new screen update data- is wrong and doesnt belong there.

Ive seen the issue with SDL /SDL2 as well.

GL is pretty universal- dont sweat the pascal.
[testLazGraph.pas.zip](https://github.com/xqemu/xqemu/files/3234295/testLazGraph.pas.zip)

**Comment by JayFoxRox** [comment]
> dont use Xgl

[Xgl has been unsupported for more than 10 years](https://en.wikipedia.org/wiki/Xgl).

We don't use it.

If you GL implementation issue uses it: not our problem.

>  GLU,GLEW,GLUT,freeglut(or glfw)

These are all fundamentally different things. So this statement makes no sense.

Read their documentation.

> it looks like X11 graphics are rendering onto a GL context.

Again: We don't do that. If your Window-Manager does that: fine. We respect GL contexts and if you have anything running that doesn't, avoid it.
If you catch us doing stuff which doesn't respect the spec, provide us with information - however, we don't do this intentionally and there's no hint that we do it either. Even apitrace and RenderDoc, deal with it just fine.

> YOu should be using one provided by qemu for the simulated gfx buffer- not trying to render onto a GL context directly.

You can't render into a GL context. And how you display, and how you render, are different things, using different APIs.

> or trying to write to the physical screen via nv instructions(im on ATI hardware)

There's no such thing in XQEMU. As far as I know, we don't even use any NV specific extensions.

> But im not sure its an Xgl issue-(although syntacticly XGL is a mess compared to the alternative) its a GL issue- for sure.

It's a user issue. But this is (as-is) a bug-tracker.

If you think this is an issue with our code, describe your environment, steps to reproduce, .. *after* consulting with us via our support channels (check our website). If you are a developer, then also provide additional information about possible causes / code review. If you don't, or aren't capable to do so, don't do it.

> The issue that we are over rendering- choking system resources. X11- as the window manager- doesnt like this- but cant stop us.

We don't. And X11 isn't a window manager either.

> -but we have to render in a loop sometimes-

This is possible and allowed. Most realtime applications do this.

> Neither SDL nor GL nor GLUT programmers seem be working thru this issue.

SDL and GLUT do. With different styles (wait-for-V-Blank-function / Callbacks). These are acceptable solutions.

GL is a rendering API - it doesn't care about the time aspect (it takes care of "what to draw"; not "when to draw" or "how to display").

> I just hit the bug with this demo code- mind you in pascal(fpc). nm the unit its supposed to work with- (it appears library chaining is impossible with OGL contexts?)

This is unrelated to XQEMU. If you need help with your Pascal code, ask elsewhere. Don't abuse our bug-tracker.

> When you render continuously- you CAUSE this issue.

This is wrong. Please read the GL spec about what GL does. Then read the GLX / WGL / CGL / EGL / .. specs to see what those APIs do / what they allow.
Then also read about X11 / Wayland or Win32 Windows, to see what those allow (in particular message queues and threading).

XQEMU respects these limits. We had no reports of it not working. There could be issues on some drivers that have plagued similar projects, but those would likely be bugs in the drivers.
RenderDoc also needs some special hacks for XQEMU, but these are bugs in RenderDoc related to multi-GL-context applications.

---

@mborgerson has provided a good answer. But his follow up questions were not answered.

My statement hopefully answers any remaining questions and points out problems in this issue:

These are just random ramblings and in no way productive.
This issue also doesn't meet our quality expectations for bug reports.

Even if there is an issue in XQEMU, this topic would be describing it too poorly to find a solution.
On our user support channels, such matters can usually be resolved quickly; I'm rather confident it's a user issue (if at all) - not a code issue in XQEMU.

Closed.
