### ISSUE TITLE
xbox hdd

### ISSUE THREAD

**Issue by JazzMaster** [xqemu/xqemu#230]
Im not saying distribute this either.

But a how-to on how to construct a basic empty hdd would be nice. I have done it- but I forget how. My hdd is dumped from a 1.6 softmod. eeprom is the only thing that seems to break xqemu.

This said:
theres an issue w qemu settings that took me hours to figure out:

IDE 0 and IDE1 drive positions etc etc that qemu gives are incorrect. Either one or the other seems to work- never both. This is wrong. IDE can and should work with both.

HDDMaker disc that I have-for rebuilding the hdd- finds two optical drives.
cromwell boots the bios- finds the hdd- but not the optical drive. The drive shows up- but never boots(disc/drive not ready/not present)

Need to look into this.

as per launch settings- try this. It tries to boot slayers mod disc(iso or raw disc is fine) and then hits a xgl/x11 issue. So clearly both my settings(stock bios, 1.0 eeprom as provided- and custom hdd from softmod 16) and xqemu is otherwise working.

consider 128 mem a modded xbox- variants do exist. default is 64.
xbox gamepad is working- as is input. Thanks for the fix.
mcpx version 11- from xbins(dont ask- look for it) has no difference on booting.

---
./xqemu/i386-softmmu/qemu-system-i386 \
-cpu pentium3 \
-m 128 \
-machine xbox,short-animation,bootrom=mcpx_rom.bin \
-bios xbox_bios-stock.bin \
-usb \
-device usb-xbox-gamepad-sdl,index=0 \
-drive file=slayers.iso,if=ide,index=1,media=cdrom \
-drive file=myhdd.qcow2,if=ide,index=0,media=disk,locked=on \
-display sdl \
-vga qxl \
-boot c

**Comment by JazzMaster** [comment]
by emoty I mean msft xbox "empty" with no saves on the drive. A bootable MSFT factory wiped dash. I may have used slayers disc- on a real unit- to get this, then cloned the hdd over somehow(ftp?)

**Comment by Ernegien** [comment]
I believe this is what you're looking for - https://github.com/xqemu/xqemu-hdd-image

**Comment by mborgerson** [comment]
Yes, please see the xqemu-hdd-image repo. It has full instructions and a downloadable image.

**Comment by JayFoxRox** [comment]
To add to this: If you need user support, use the Discord for users, that's linked from our website.

This is a bugtracker, not a support channel.

Also stop bringing up providers of illegal content - we will report such incident to GitHub if need be, and you will be banned / there can be legal consequences.
