### ISSUE TITLE
[WinError 10061] No Connection Could Be Made Because The Target Machine Actively Refused It

### ISSUE THREAD

**Issue by SuMedic** [xqemu/xqemu#237]
on start from the manager app, tried disabling firewall and messing with what settings are available to no avail.

**Comment by dracc** [comment]
- If XQEMU fails to launch via XQEMU-Manager ("[WinError 10061] No connection could be made because the target machine actively refused it"), please provide us with the content of the "CLI"-Tab in the "Settings" dialog, so we can assist you.

MCPX:
- Ensure your MCPX is version 1.0

Flash / bios / kernel:
- Ensure your kernel is compatible with Xbox 1.0

**Comment by SuMedic** [comment]
D:/XQEMU/xqemuw.exe -cpu pentium3 -machine xbox,accel=kvm:hax:whpx,kernel_irqchip=off,bootrom=D:/XQEMU/MCPXV1.1_FULL.BIN,short_animation -m 64M -bios D:/XQEMU/xbox.bin -drive file=D:/XQEMU/xbox_hdd.qcow2,index=0,media=disk -drive index=1,media=cdrom -qmp tcp:localhost:4444,server,nowait -display sdl -device usb-hub,port=3 -device usb-xbox-gamepad-sdl,index=0,port=3.1 -device usb-xbox-gamepad-sd1, index=0

the last line "usb-xbox-gamepad-sd1, index=0" was added by me, i tried launching with and without with no difference

**Comment by GXTX** [comment]
This seems like a user support issue and not a problem with the emulator, especially now seeing your command line.

Please make sure you fully read the docs located [here](https://xqemu.com/getting-started/). If you need more support we do have a user orientated Discord server [here](https://discord.gg/4aZYj74).

**Comment by mborgerson** [comment]
This is more of an issue with xqemu-manager failing to connect to the xqemu instance because xqemu failed to start for some reason. We need to add better error handling to xqemu-manager to inform the user of such problems. This issue is captured here: https://github.com/xqemu/xqemu-manager/issues/6
