### ISSUE TITLE
"readlink: illegal option -- f" in build.sh on macOS

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/xqemu#242]
This is seen in CI logs for macOS:

```
Compiling for MacOS…
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

* [Example in successful log](https://travis-ci.org/GXTX/xqemu/jobs/545694571#L110)
* [Example in failed log](https://travis-ci.org/GXTX/xqemu/jobs/549266906#L471)

The error must come from here:

https://github.com/xqemu/xqemu/blob/cfef2c3e4a0b01c1959e79b6374161bd56234448/build.sh#L63-L66

Someone should look into it (and fix it).

**Comment by thrimbor** [comment]
macOS's readlink (which comes from FreeBSD afaik) doesn't support the `-f` option. I've fixed an issue like this in another project a while ago by installing the `coreutils` homebrew package and running `alias readlink='greadlink'` in the buildscript when macOS was detected (greadlink is the GNU-version of readlink, which supports `-f`).
