### ISSUE TITLE
Stargate SG-1 The Alliance debug build Crash

### ISSUE THREAD

**Issue by Eldritch-Jam** [xqemu/xqemu#276]
Game shows two splash screens, then XQEMU quits prematurely with this in the log. it must be run with a debug rom, and 128MiB of ram.
Also I compiled this build of XQEMU myself, so it is entirely possible that I made a rookie mistake.

`dsp_init
dsp_init
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
ac97: invalid bm_index(3) in voice_set_active
**
ERROR:C:/msys64/home/jamma/xqemu/hw/xbox/nv2a/nv2a_shaders.c:551:generate_fixed_function: assertion failed: (0)
Bail out! ERROR:C:/msys64/home/jamma/xqemu/hw/xbox/nv2a/nv2a_shaders.c:551:generate_fixed_function: assertion failed: (0)
`

Splash screen shown before crash:
![screenshot 2](https://user-images.githubusercontent.com/61929504/76157894-b126fb80-6163-11ea-9c7c-b2d68ff9df63.png)

**Comment by dracc** [comment]
We don't want piracy links around here.

**Comment by Ernegien** [comment]
@Eldritch-Jam please remove your ISO link, thanks ;)

**Comment by JayFoxRox** [comment]
I'm closing this issue:

* It's not a crash: It's XQEMU reporting that a hardware feature used by the game is not implemented yet.
* Issues on the XQEMU issue tracker are *typically* tracking the implementation status of missing hardware features. I have created #277 to track this issue.
* This game was unreleased and likely illegally downloaded (which we don't condone). I *personally* wouldn't want to promote pirating of this game by resolving this issue specifically for this game.

Closed.
