### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by MinecraftW06** [xqemu/xqemu#279]
Pls help me!

I want to open xbox dashboard with it, but it just say "Please insert an Xbox disc", and the loading screen is laggy.
Can anyone tell me how to open dashboard?
Is it worked to anyone?

Thanks!

![Névtelen](https://user-images.githubusercontent.com/65031582/81422306-13e04780-9153-11ea-834d-9383996ddc63.png)

**Comment by GXTX** [comment]
This really sounds like a user error and GitHub really isn't the place for those. Checkout the website to learn more and to find a link to our Community Discord server.

https://xqemu.com/

**Comment by JayFoxRox** [comment]
Not an issue with XQEMU: You have to provide your own ROMs (and clearly you already have MCPX and BIOS).
I've removed illegal portions of your post. We do not tolerate your illegal activities.

The dashboard in particular is on the HDD. So also dump that.

Closed.
