### ISSUE TITLE
Grand Theft Auto San Andreas Assertion Failed

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [xqemu/xqemu#38]
I have got exception after pressing Start:
MinGW Runtime Assertion
Assertion failed!
Program: D:\xb\xqemu2.0\xqemu.exe
File: C:/projects/xqemu-c5j6o/hw/xbox/dsp/dsp_cpu.c, Line 1018
Expression: address < DSP_XRAM_SIZE

Tested on latest 5d4058d, tested with bat-file, not xqemu manager (with xqemu-manager it stucks after copyright screen).
Here is bat-file content, maybe it can help to fix xqemu-manager:
`xqemu.exe -cpu pentium3 -machine xbox,short_animation,bootrom=mcpx.bin -bios bios.bin -m 64 -drive index=0,media=disk,file=hdd.qcow2,locked -drive index=1,media=cdrom,file=gtasa.iso -usb -device usb-xbox-gamepad`

**Comment by JayFoxRox** [comment]
Please always provide information which commit / revision of XQEMU is used.
Otherwise ` File: C:/projects/xqemu-c5j6o/hw/xbox/dsp/dsp_cpu.c, Line 1018` (which is the most important part) does not help us.
Thanks!

**Comment by gandalfthewhite19890404** [comment]
Latest 5d4058d, tested with bat-file, not xqemu manager (with xqemu-manager it stucks after copyright screen).

**Comment by JayFoxRox** [comment]
Looks like this was solved, as reported in https://github.com/xqemu/xqemu/pull/92#issuecomment-408762985

Closed.
