### ISSUE TITLE
NV2A PTIMER is broken

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/xqemu#43]
The timer returns bad values. I remember fixing this in my own code a while ago; but my changes never went upstream.

You can use https://github.com/JayFoxRox/xbox-tools/pull/50 to compare the behaviour to real hardware.

**Comment by 0DaveX** [comment]
Can this be closed?
https://github.com/xqemu/xqemu/pull/113

**Comment by JayFoxRox** [comment]
Yes, I think so.
I've marked this as a bug, because the broken behaviour was a bug in existing code.

Closed.
