### ISSUE TITLE
NV2A Window clipping is broken

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/xqemu#44]
Running https://github.com/xqemu/xqemu/commit/5d4058d6f25ec09be8a3e581cc02b419a89e2fe0 ; the right half of the display is broken in this screenshot:

![Right half broken](https://cdn.discordapp.com/attachments/428359372842991616/460895106040332319/unknown.png)

*(Screenshot provided by @DarkGabbz)*

This is due to broken window clipping (which was merged in a premature state).
Even if it's not actually a regression, it will be observed as one in most applications (as window clipping usually contributes little, but can break a lot).

---

I believe this issue is due to anti-aliasing in combination with the clipping; which was never tested.

As the actual clipping uses OpenGL pixel coordinates, it has to respect anti-aliasing (which it currently doesn't). So [these uniforms need `pgraph_apply_anti_aliasing_factor`](https://github.com/xqemu/xqemu/commit/c50738b732bd830223691cc317fa60dc112031cc#diff-d936f94a7fe1cbc634cedf01266670e5R3157).

The independence of the clipping optimization (which only scans for redundant regions) and implementation / uniform upload (which does clipping) should also be made more clear in the source code, by adding a comment near the optimization loop.
There should be a short review here though, because I have written this code a long time ago, and it might actually do more than optimizing I could have forgotten about.

That said, I believe the clipping optimization should not respect anti-aliasing. It works with coordiantes (`surface_shape.clip_width` and `surface_shape.clip_height`) which are not affected by anti-aliasing (unless our `surface_shape` is bad).
If optimization / implementation are really independent, then regardless of this issue, [this comment should be removed](https://github.com/xqemu/xqemu/commit/c50738b732bd830223691cc317fa60dc112031cc#diff-d936f94a7fe1cbc634cedf01266670e5R3066) or moved to the actual implementation (but that has been solved by my above observation probably).

**Comment by mborgerson** [comment]
Clipping support has been reverted from master branch until these regressions can be resolved. The original commit is available here: https://github.com/mborgerson/xqemu/tree/nv2a-clipping
