### ISSUE TITLE
Main window should show "XQEMU" in title bar and XQEMU icon

### ISSUE THREAD

**Issue by mborgerson** [xqemu/xqemu#49]
Need to update the main window titlebar with XQEMU and the XQEMU icon (tbd)

**Comment by dracc** [comment]
I've started doing a little work on this. Title updated, will try to figure out #47 this evening and await a decision on what logo we want to use.

**Comment by mborgerson** [comment]
@dracc Thanks, your changes should still apply but do be aware that I'm working on a custom SDL2-GL ui driver, so make sure you're updating the SDL2 stuff and not any of the other UI drivers. As for the logo, it should be reading from a logo.bmp IIRC, so we just need to swap that out.

**Comment by dracc** [comment]
Worth noting; the icon portion of this issue remains. I have code available to fix it, but we must settle on a logo first.
