### ISSUE TITLE
Add developer documentation

### ISSUE THREAD

**Issue by mborgerson** [xqemu/xqemu#5]
Solid documentation is badly needed. This would be a great way to attract new developers and get them up to speed quickly. Possible something like [Read the Docs](https://readthedocs.org/) can be used for this.

Things this should cover:
* Basic system init flow (very basics how Qemu devices are created, bus init, device init)
* What the main source files are
* High to medium level on how nv2a works, how nvnet works, how XYZ works...
* Debugging techniques (how to use KD, how to debug on real hardware (nxdk-rdt possibly))

Update: the new [xqemu.com](http://xqemu.com) site is live! This project level documentation should be added there.

Low-level details about the nv2a architecture should probably end up going back to the [envytools project](http://envytools.readthedocs.io/en/latest/hw/). Other low-level details might be better suited for the [XboxDevWiki](http://xboxdevwiki.net/Main_Page).

**Comment by JayFoxRox** [comment]
I actually forgot that we moved the docs the website before making some changes to our Wiki.
Shall we close our Wiki completly and refer to our website instead?

Also I suggest moving this issue to the website repo and linking to the website docs from our xqemu/xqemu README.

**Comment by mborgerson** [comment]
The wiki may still have some value, but yes, I think I would rather have everything on the website. That's fine, I'll just close this for now.
